// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/lyj404/gin-api-template/api/handler"
	"github.com/lyj404/gin-api-template/api/middleware"
	"github.com/lyj404/gin-api-template/api/route"
	"github.com/lyj404/gin-api-template/domain"
	"github.com/lyj404/gin-api-template/domain/services"
	"github.com/lyj404/gin-api-template/global"
	"github.com/lyj404/gin-api-template/pkg/lib/logger"
	"github.com/lyj404/gin-api-template/repository"
	"github.com/lyj404/gin-api-template/service"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// InitializeApp 初始化应用，使用 Wire 自动生成依赖注入代码
func InitializeApp() (*App, error) {
	db := provideDB()
	client := provideRedis()
	logger := provideLogger()
	duration := provideTimeout()
	engine := provideRouter(duration, logger)
	userRepo := repository.NewUserRepo(db)
	loginService := service.NewUserService(userRepo, duration)
	refreshTokenService := service.NewRefreshTokenService(userRepo, duration)
	auditLogRepository := repository.NewAuditLogRepository()
	auditLogService := service.NewAuditLogService(auditLogRepository)
	userHandler := handler.NewUserHandler(loginService, refreshTokenService, auditLogService)
	refreshTokenHandler := handler.NewRefreshTokenHandler(refreshTokenService)
	roleRepository := repository.NewRoleRepository()
	roleService := service.NewRoleService(roleRepository)
	roleHandler := handler.NewRoleHandler(roleService)
	orgUnitRepository := repository.NewOrgUnitRepository()
	orgUnitService := service.NewOrgUnitService(orgUnitRepository)
	orgUnitHandler := handler.NewOrgUnitHandler(orgUnitService)
	auditLogHandler := handler.NewAuditLogHandler(auditLogService)
	permissionService := service.NewPermissionService()
	userPermissionHandler := handler.NewUserPermissionHandler(permissionService)
	userProfileService := service.NewUserProfileService()
	userProfileHandler := handler.NewUserProfileHandler(userProfileService)
	menuRepository := repository.NewMenuRepository()
	menuService := service.NewMenuService(menuRepository)
	menuHandler := handler.NewMenuHandler(menuService)
	userRepository := repository.NewUserManagementRepository()
	userManagementService := service.NewUserManagementService(userRepository)
	userManagementHandler := handler.NewUserManagementHandler(userManagementService)
	resourceRepository := repository.NewResourceRepository()
	resourceService := service.NewResourceService(resourceRepository)
	resourceHandler := handler.NewResourceHandler(resourceService)
	dashboardHandler := handler.NewDashboardHandler()
	rbacMiddleware := middleware.NewRBACMiddleware(permissionService)
	v := provideRouteRegistration(engine, userHandler, refreshTokenHandler, roleHandler, orgUnitHandler, auditLogHandler, userPermissionHandler, userProfileHandler, menuHandler, userManagementHandler, resourceHandler, dashboardHandler)
	app := &App{
		DB:             db,
		Redis:          client,
		Logger:         logger,
		Router:         engine,
		UserRepo:       userRepo,
		UserSvc:        loginService,
		TokenSvc:       refreshTokenService,
		UserHdlr:       userHandler,
		RefreshHdlr:    refreshTokenHandler,
		RoleHdlr:       roleHandler,
		OrgHdlr:        orgUnitHandler,
		AuditHdlr:      auditLogHandler,
		UserPermHdlr:   userPermissionHandler,
		UserProfileHdlr: userProfileHandler,
		MenuHdlr:       menuHandler,
		UserMgmtHdlr:   userManagementHandler,
		ResourceHdlr:   resourceHandler,
		DashboardHdlr:  dashboardHandler,
		RBACMiddleware: rbacMiddleware,
		PermSvc:        permissionService,
		RegisterRoutes: v,
	}
	return app, nil
}

// wire.go:

// App 应用结构体，包含所有依赖
type App struct {
	DB             *gorm.DB
	Redis          *redis.Client
	Logger         *zap.Logger
	Router         *gin.Engine
	UserRepo       domain.UserRepo
	UserSvc        domain.LoginService
	TokenSvc       domain.RefreshTokenService
	UserHdlr       *handler.UserHandler
	RefreshHdlr    *handler.RefreshTokenHandler
	RoleHdlr       *handler.RoleHandler
	OrgHdlr        *handler.OrgUnitHandler
	AuditHdlr      *handler.AuditLogHandler
	UserPermHdlr   *handler.UserPermissionHandler
	UserProfileHdlr *handler.UserProfileHandler
	MenuHdlr       *handler.MenuHandler
	UserMgmtHdlr   *handler.UserManagementHandler
	ResourceHdlr   *handler.ResourceHandler
	DashboardHdlr  *handler.DashboardHandler
	RBACMiddleware *middleware.RBACMiddleware
	PermSvc        services.PermissionService
	RegisterRoutes func()
}

// provideDB 提供 DB 实例
func provideDB() *gorm.DB {
	return global.G_DB
}

// provideRedis 提供 Redis 实例
func provideRedis() *redis.Client {
	return global.G_REDIS
}

// provideLogger 提供 Logger 实例
func provideLogger() *zap.Logger {
	return logger.InitZapLogger()
}

// provideRouter 提供 Router 实例，初始化路由和中间件
func provideRouter(timeout time.Duration, logger2 *zap.Logger) *gin.Engine {
	return route.SetUp(timeout, logger2)
}

// provideRouteRegistration 提供路由注册函数
func provideRouteRegistration(
	router *gin.Engine,
	userHdlr *handler.UserHandler,
	refreshTokenHdlr *handler.RefreshTokenHandler,
	roleHdlr *handler.RoleHandler,
	orgHdlr *handler.OrgUnitHandler,
	auditHdlr *handler.AuditLogHandler,
	userPermHdlr *handler.UserPermissionHandler,
	userProfileHdlr *handler.UserProfileHandler,
	menuHdlr *handler.MenuHandler,
	userMgmtHdlr *handler.UserManagementHandler,
	resourceHdlr *handler.ResourceHandler,
	dashboardHdlr *handler.DashboardHandler,
) func() {
	return func() {

		publicGroup := router.Group("")
		route.NewUserRouter(userHdlr, refreshTokenHdlr, publicGroup)

		protectedGroup := router.Group("")
		protectedGroup.Use(route.JwtAuthMiddleware())
		route.NewRoleRouter(roleHdlr, protectedGroup)
		route.NewOrgUnitRouter(orgHdlr, protectedGroup)
		route.NewAuditLogRouter(auditHdlr, protectedGroup)
		route.NewUserPermissionRouter(userPermHdlr, userProfileHdlr, protectedGroup)
		route.NewMenuRouter(menuHdlr, protectedGroup)
		route.NewUserManagementRouter(userMgmtHdlr, protectedGroup)
		route.NewResourceRouter(resourceHdlr, protectedGroup)
		route.NewDashboardRouter(dashboardHdlr, protectedGroup)
	}
}

// provideTimeout 提供超时时间
func provideTimeout() time.Duration {
	return time.Duration(10) * time.Second
}

// providerSet 依赖注入提供者集合
var providerSet = wire.NewSet(
	provideDB,
	provideRedis,
	provideLogger,
	provideRouter,
	provideRouteRegistration,
	provideTimeout, repository.NewUserRepo, repository.NewRoleRepository, repository.NewOrgUnitRepository, repository.NewAuditLogRepository, repository.NewMenuRepository, repository.NewUserManagementRepository, repository.NewResourceRepository, service.NewUserService, service.NewRefreshTokenService, service.NewPermissionService, service.NewRoleService, service.NewOrgUnitService, service.NewAuditLogService, service.NewMenuService, service.NewUserManagementService, service.NewUserProfileService, service.NewResourceService, middleware.NewRBACMiddleware, handler.NewUserHandler, handler.NewRefreshTokenHandler, handler.NewRoleHandler, handler.NewOrgUnitHandler, handler.NewUserPermissionHandler, handler.NewUserProfileHandler, handler.NewAuditLogHandler, handler.NewMenuHandler, handler.NewUserManagementHandler, handler.NewResourceHandler, handler.NewDashboardHandler,
)
