// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/lyj404/gin-api-template/api/handler"
	"github.com/lyj404/gin-api-template/config"
	"github.com/lyj404/gin-api-template/domain"
	"github.com/lyj404/gin-api-template/global"
	"github.com/lyj404/gin-api-template/repository"
	"github.com/lyj404/gin-api-template/service"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db := provideDB()
	userRepo := repository.NewUserRepo(db)
	duration := provideTimeout()
	loginService := service.NewUserService(userRepo, duration)
	refreshTokenService := service.NewRefreshTokenService(userRepo, duration)
	userHandler := handler.NewUserHandler(loginService, refreshTokenService)
	helloHandler := handler.NewHelloHandler()
	refreshTokenHandler := handler.NewRefreshTokenHandler(refreshTokenService)
	app := &App{
		DB:          db,
		UserRepo:    userRepo,
		UserSvc:     loginService,
		TokenSvc:    refreshTokenService,
		UserHdlr:    userHandler,
		HelloHdlr:   helloHandler,
		RefreshHdlr: refreshTokenHandler,
	}
	return app, nil
}

// wire.go:

type App struct {
	DB          *gorm.DB
	UserRepo    domain.UserRepo
	UserSvc     domain.LoginService
	TokenSvc    domain.RefreshTokenService
	UserHdlr    *handler.UserHandler
	HelloHdlr   *handler.HelloHandler
	RefreshHdlr *handler.RefreshTokenHandler
}

func provideDB() *gorm.DB {
	return global.G_DB
}

func provideTimeout() time.Duration {
	return time.Duration(config.CfgTimeout.ContextTimeout) * time.Second
}

var providerSet = wire.NewSet(
	provideDB,
	provideTimeout, repository.NewUserRepo, service.NewUserService, service.NewRefreshTokenService, handler.NewUserHandler, handler.NewHelloHandler, handler.NewRefreshTokenHandler,
)
